export const Defaults = {
  user: {
    id: "",
    accesslevel: 0,
    phonenumber: "",
  },
  profile: {
    firstname: "",
    lastname: "",
    email: "",
    bio: "",
    birthdate: "",
  },
  types: {
    COW: "Үхэр",
    GOAT: "Ямаа",
    SHEEP: "Хонь",
    CAMEL: "Тэмээ",
    PET: "Тэжээвэр",
    HORSE: "Адуу",
  },
  address: {
    phone: "",
    State: "",
    province: "",
    city: "",
    sum_or_district: "",
    zip: "",
  },
  herd: {
    _id: "",
    type: "",
    age: "",
    color: "",
    weight: "",
    height: "",
    price: 0,
    amount: "",
    description: "",
    ads_type: "",
    contact: "",
  },
};
export const herds = [
  { type: Defaults.types.GOAT, name: "Ямаа" },
  {
    type: Defaults.types.SHEEP,
    name: "Хонь",
  },
  {
    type: Defaults.types.COW,
    name: "Үхэр",
  },
  { type: Defaults.types.HORSE, name: "Aдуу" },
  { type: Defaults.types.CAMEL, name: "Тэмээ" },
];
export const fivestar = [
  { key: "m", text: "🐑 Хонь", value: "Хонь" },
  { key: "f", text: "🐐 Ямаа", value: "Ямаа" },
  { key: "co", text: "🐄 Үхэр", value: "Үхэр" },
  { key: "ca", text: "🐫 Тэмээ", value: "Тэмээ" },
  { key: "h", text: "🐎 Адуу", value: "Адуу" },
  { key: "t", text: "🐾 Тэжээвэр", value: "Тэжээвэр" },
];
export const Provinces = [
  { key: 0, text: "УлаанБаатар", value: "УлаанБаатар" },
  { key: 1, text: "Архангай", value: "Архангай" },
  { key: 2, text: "Баян-Өлгий", value: "Баян-Өлгий" },
  { key: 3, text: "Баянхонгор", value: "Баянхонгор" },
  { key: 4, text: "Булган", value: "Булган" },
  { key: 5, text: "Говь-Алтай", value: "Говь-Алтай" },
  { key: 6, text: " 	Говьсүмбэр", value: " 	Говьсүмбэр" },
  { key: 7, text: " 	Дархан-Уул", value: " 	Дархан-Уул" },
  { key: 8, text: "Дорноговь", value: "Дорноговь" },
  { key: 9, text: "Дорнод", value: "Дорнод" },
  { key: 10, text: "Дундговь", value: "Дундговь" },
  { key: 11, text: "Завхан", value: "Завхан" },
  { key: 12, text: "Орхон", value: "Орхон" },
  { key: 13, text: "Өвөрхангай", value: "Өвөрхангай" },
  { key: 14, text: "Өмнөговь", value: "Өмнөговь" },
  { key: 15, text: "Сүхбаатар", value: "Сүхбаатар" },
  { key: 16, text: "Сэлэнгэ", value: "Сэлэнгэ" },
  { key: 17, text: "Төв", value: "Төв" },
  { key: 18, text: "Увс", value: "Увс" },
  { key: 19, text: "Ховд", value: "Ховд" },
  { key: 20, text: "Хөвсгөл", value: "Хөвсгөл" },
  { key: 21, text: "Хэнтий", value: "Хэнтий" },
];
